<h1>Notebook dedicato all'aggiunta di nuove features blockchain</h1>

In [27]:
#partiamo da mirrorPublications_authors.csv
import pandas as pd
df = pd.read_csv("mirrorPublications_authors.csv")
df.fillna(0, inplace=True)

df

,Writing NFT,Author Homepage,Total Sold(ETH),Total Sold Numbers,Total Buyers,Price(ETH),nft_address,collection,fees,created_date,...,var%_btc,last_eth_usd,open_eth_usd,max_eth_usd,min_eth_usd,vol_eth,var%_eth,authorPostCount,authorTotalSales,authorTotalRevenue
0,https://opensea.io/assets/optimism/0x26bbb507d...,https://mirror.xyz/0xf4cdb62c9a66c749cdf736c43...,0.5900,59,53,0.0100,0x26bbb507daa7c0dec6a578a09f0d7ac85ff6fec5,man1f3st0,"[2.5, 10.0]",2022-08-16,...,-1.02,1876.70,1900.08,1914.06,1856.44,725780.0,-1.24,1,59,0.5900
1,https://opensea.io/assets/optimism/0xfcba4d13f...,https://mirror.xyz/0x0287132a8c92e811d94e461b0...,0.0001,1,1,0.0001,0xfcba4d13fa7e4933ebf709f26d20423e5fb38f03,token-of-wealth,"[2.5, 10.0]",2022-08-16,...,-1.02,1876.70,1900.08,1914.06,1856.44,725780.0,-1.24,1,1,0.0001
2,https://opensea.io/assets/optimism/0xe6d34d7f3...,https://mirror.xyz/0x3f9da1a56fac7efae92c84c90...,0.0050,1,1,0.0050,0xe6d34d7f3c34f6d90e311e302ce160b5214c2ba0,coinslist-airdrop-nft,"[2.5, 10.0]",2022-08-16,...,-1.02,1876.70,1900.08,1914.06,1856.44,725780.0,-1.24,1,1,0.0050
3,https://opensea.io/assets/optimism/0x5daa524dd...,https://mirror.xyz/0xc065e02d562cc390f35693059...,0.0000,282,280,0.0001,0x5daa524dd35c0b51bac36f76e8ff89dd4866f12e,mobile-launch-trading-competition,"[2.5, 10.0]",2022-08-16,...,-1.02,1876.70,1900.08,1914.06,1856.44,725780.0,-1.24,65,5765,0.0000
4,https://opensea.io/assets/optimism/0xee07e40fe...,https://mirror.xyz/0x4ced9817cad891aeffbf5fb7d...,1.0000,100,93,0.0100,0xee07e40fe43ef1b1d5ed018a881742462f8cd8e3,note-is-a-key-component-of-cantos-free-public-...,"[2.5, 10.0]",2022-08-16,...,-1.02,1876.70,1900.08,1914.06,1856.44,725780.0,-1.24,32,2768,6.4400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,https://opensea.io/assets/optimism/0xd84035bc2...,https://mirror.xyz/0x489e3e846bb550cb7b023108c...,0.0000,5,5,0.0001,0xd84035bc253d7ab99d3e05c1d1f6d1185300a602,the-governance-staking-era,[2.5],2024-11-18,...,0.72,3207.46,3075.42,3220.65,3052.29,698670.0,4.29,16,235,0.0000
26871,https://opensea.io/assets/optimism/0x3403ab72d...,https://mirror.xyz/0x5ee94b80d60880f25048b6158...,0.0000,1,1,0.0001,0x3403ab72df88717d4b9067fc08daf07949bab830,superchain-sunday-week-46-2024,[2.5],2024-11-18,...,0.72,3207.46,3075.42,3220.65,3052.29,698670.0,4.29,58,204,0.0000
26872,https://opensea.io/assets/optimism/0x9fff9c16f...,https://mirror.xyz/0x9ad0cb287b57828a2fb2b738d...,0.0000,4,4,0.0001,0x9fff9c16fde288329a2b663697ef2d04e967b4a9,the-morpho-dao-to-enable-transferability-for-m...,[2.5],2024-11-18,...,0.72,3207.46,3075.42,3220.65,3052.29,698670.0,4.29,13,28,0.0000
26873,https://opensea.io/assets/optimism/0x81457615f...,https://mirror.xyz/0xd5f09257a7b7d070c39e6b473...,0.0000,2,2,0.0001,0x81457615fcd852e1d51ec8273d0ef6e95e4a7da6,unlock-the-full-potential-of-safe-wallet-sign-...,[2.5],2024-11-18,...,0.72,3207.46,3075.42,3220.65,3052.29,698670.0,4.29,5,192,0.0000
26874,https://opensea.io/assets/optimism/0x444e61b43...,https://mirror.xyz/0x506cf76ab79b1e777bb64c173...,0.0000,1,1,0.0001,0x444e61b4386718d35384ffa3a7bac710c22d703f,how-to-play-constellation-battle-on-fuel,[2.5],2024-11-18,...,0.72,3207.46,3075.42,3220.65,3052.29,698670.0,4.29,1,1,0.0000

<h2>Aggiungo informazioni sui valori di Optimism, Tether, USDC, DAI e Arbitrum in USD</h2>

In [29]:
#tutti presi da investing.com
optimism_info = pd.read_csv("optimism.csv")
tether_info = pd.read_csv("tether.csv")
usdc_info = pd.read_csv("usdc.csv")
dai_info = pd.read_csv("dai.csv")
#arbitrum_info = pd.read_csv("arbitrum.csv") ---> scartato perché ha troppe nan

#usdc_info ha 26 NaN su volume, le riempio con la moda, il valore più frequente
mode_value = usdc_info['Vol.'].mode()[0]
usdc_info['Vol.'] = usdc_info['Vol.'].fillna(mode_value)

In [30]:
#rinomino le colonne dei df per chiarezza una volta che le unirò al mio df principale. cambio Data in created_date per poterli poi unire al df principale
optimism_info = optimism_info.rename(columns={
    'Data': 'created_date',
    'Ultimo': 'last_optimism_usd',
    'Apertura': 'open_optimism_usd',
    'Massimo': 'max_optimism_usd',
    'Minimo': 'min_optimism_usd',
    'Vol.': 'vol_optimism',
    'Var. %': 'var%_optimism'
})

tether_info = tether_info.rename(columns={
    'Data': 'created_date',
    'Ultimo': 'last_tether_usd',
    'Apertura': 'open_tether_usd',
    'Massimo': 'max_tether_usd',
    'Minimo': 'min_tether_usd',
    'Vol.': 'vol_tether',
    'Var. %': 'var%_tether'
})

usdc_info = usdc_info.rename(columns={
    'Data': 'created_date',
    'Ultimo': 'last_usdc_usd',
    'Apertura': 'open_usdc_usd',
    'Massimo': 'max_usdc_usd',
    'Minimo': 'min_usdc_usd',
    'Vol.': 'vol_usdc',
    'Var. %': 'var%_usdc'
})

dai_info = dai_info.rename(columns={
    'Data': 'created_date',
    'Ultimo': 'last_dai_usd',
    'Apertura': 'open_dai_usd',
    'Massimo': 'max_dai_usd',
    'Minimo': 'min_dai_usd',
    'Vol.': 'vol_dai',
    'Var. %': 'var%_dai'
})

#arbitrum_info = arbitrum_info.rename(columns={
#    'Data': 'created_date',
#    'Ultimo': 'last_arbitrum_usd',
#    'Apertura': 'open_arbitrum_usd',
#    'Massimo': 'max_arbitrum_usd',
#    'Minimo': 'min_arbitrum_usd',
#    'Vol.': 'vol_arbitrum',
#    'Var. %': 'var%_arbitrum'
#})

In [31]:
#modifico la colonna "created_date" per cambiare il formato della data da gg.mm.aaaa a aaaa-mm-gg in maniera da essere uguale a created_date del df originale, per poter poi unire facilmente i dataset
optimism_info["created_date"] = pd.to_datetime(optimism_info["created_date"], format="%d.%m.%Y").dt.strftime("%Y-%m-%d")
tether_info["created_date"] = pd.to_datetime(tether_info["created_date"], format="%d.%m.%Y").dt.strftime("%Y-%m-%d")
usdc_info["created_date"] = pd.to_datetime(usdc_info["created_date"], format="%d.%m.%Y").dt.strftime("%Y-%m-%d")
dai_info["created_date"] = pd.to_datetime(dai_info["created_date"], format="%d.%m.%Y").dt.strftime("%Y-%m-%d")
#arbitrum_info["created_date"] = pd.to_datetime(arbitrum_info["created_date"], format="%d.%m.%Y").dt.strftime("%Y-%m-%d")

#unisco i df usando 'created_date' come chiave
df = df.merge(optimism_info[['created_date', 'last_optimism_usd', 'open_optimism_usd', 'max_optimism_usd', 'min_optimism_usd', 'vol_optimism', 'var%_optimism']],
                     on='created_date', how='left')

df = df.merge(tether_info[['created_date', 'last_tether_usd', 'open_tether_usd', 'max_tether_usd', 'min_tether_usd', 'vol_tether', 'var%_tether']],
                            on='created_date', how='left')

df = df.merge(usdc_info[['created_date', 'last_usdc_usd', 'open_usdc_usd', 'max_usdc_usd', 'min_usdc_usd', 'vol_usdc', 'var%_usdc']],
                            on='created_date', how='left')

df = df.merge(dai_info[['created_date', 'last_dai_usd', 'open_dai_usd', 'max_dai_usd', 'min_dai_usd', 'vol_dai', 'var%_dai']],
                            on='created_date', how='left')

#df = df.merge(arbitrum_info[['created_date', 'last_arbitrum_usd', 'open_arbitrum_usd', 'max_arbitrum_usd', 'min_arbitrum_usd', 'vol_arbitrum', 'var%_arbitrum']],
#                            on='created_date', how='left')

#formatto il dataset una volta uniti per essere coerente con le altre colonne e utilizzabili con i miei modelli

#modifico le colonne con i prezzi rimuovendo i punti, sostituendo le virgole con i punti e convertendo in float. 1.856,44 -> 1856.44
to_modify = ['last_optimism_usd', 'open_optimism_usd', 'max_optimism_usd', 'min_optimism_usd',
             'last_tether_usd', 'open_tether_usd', 'max_tether_usd', 'min_tether_usd',
             'last_usdc_usd', 'open_usdc_usd', 'max_usdc_usd', 'min_usdc_usd',
             'last_dai_usd', 'open_dai_usd', 'max_dai_usd', 'min_dai_usd']
#'last_arbitrum_usd', 'open_arbitrum_usd', 'max_arbitrum_usd', 'min_arbitrum_usd'

for col in to_modify:
    df[col] = df[col].str.replace('.', '', regex=False)  #rimuove i punti
    df[col] = df[col].str.replace(',', '.', regex=False)  #sostituisce le virgole con i punti
    df[col] = df[col].astype(float)  #converte in float

#modifico le colonne con i volumi sostituendo le virgole con i punti, rimuovendo K/M e moltiplicando per 1000/1000000. 201,70K -> 2017000.0
to_modify_vol = ['vol_optimism', 'vol_tether', 'vol_usdc', 'vol_dai']
#'vol_arbitrum'
for col in to_modify_vol:
    df[col] = df[col].astype(str).str.replace(',', '.', regex=False)  #sostituisce la virgola con il punto
    df[col] = df[col].apply(lambda x: float(x.replace('K', '').replace('M', '').replace('B', '')) * 1000 if 'K' in x 
                        else (float(x.replace('M', '').replace('K', '').replace('B', '')) * 1000000 if 'M' in x 
                              else (float(x.replace('B', '').replace('M', '').replace('K', '')) * 1000000000 if 'B' in x 
                                    else float(x)))) #converte in float, rimuove K/M/B e moltiplica per 1000, per 1000000 o per 1000000000

#modifico le colonne con la var% sostituendo le virgole con i punti e rimuovendo il simbolo percentuale. -1,24% -> -1.24
to_modify_var = ['var%_optimism', 'var%_tether', 'var%_usdc', 'var%_dai']
#'var%_arbitrum'
for col in to_modify_var:
    df[col] = df[col].str.replace(',', '.', regex=False)  #sostituisce la virgola con il punto
    df[col] = df[col].str.replace('%', '', regex=False)  #rimuove '%'

df

,Writing NFT,Author Homepage,Total Sold(ETH),Total Sold Numbers,Total Buyers,Price(ETH),nft_address,collection,fees,created_date,...,max_usdc_usd,min_usdc_usd,vol_usdc,var%_usdc,last_dai_usd,open_dai_usd,max_dai_usd,min_dai_usd,vol_dai,var%_dai
0,https://opensea.io/assets/optimism/0x26bbb507d...,https://mirror.xyz/0xf4cdb62c9a66c749cdf736c43...,0.5900,59,53,0.0100,0x26bbb507daa7c0dec6a578a09f0d7ac85ff6fec5,man1f3st0,"[2.5, 10.0]",2022-08-16,...,1.0000,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00
1,https://opensea.io/assets/optimism/0xfcba4d13f...,https://mirror.xyz/0x0287132a8c92e811d94e461b0...,0.0001,1,1,0.0001,0xfcba4d13fa7e4933ebf709f26d20423e5fb38f03,token-of-wealth,"[2.5, 10.0]",2022-08-16,...,1.0000,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00
2,https://opensea.io/assets/optimism/0xe6d34d7f3...,https://mirror.xyz/0x3f9da1a56fac7efae92c84c90...,0.0050,1,1,0.0050,0xe6d34d7f3c34f6d90e311e302ce160b5214c2ba0,coinslist-airdrop-nft,"[2.5, 10.0]",2022-08-16,...,1.0000,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00
3,https://opensea.io/assets/optimism/0x5daa524dd...,https://mirror.xyz/0xc065e02d562cc390f35693059...,0.0000,282,280,0.0001,0x5daa524dd35c0b51bac36f76e8ff89dd4866f12e,mobile-launch-trading-competition,"[2.5, 10.0]",2022-08-16,...,1.0000,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00
4,https://opensea.io/assets/optimism/0xee07e40fe...,https://mirror.xyz/0x4ced9817cad891aeffbf5fb7d...,1.0000,100,93,0.0100,0xee07e40fe43ef1b1d5ed018a881742462f8cd8e3,note-is-a-key-component-of-cantos-free-public-...,"[2.5, 10.0]",2022-08-16,...,1.0000,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,https://opensea.io/assets/optimism/0xd84035bc2...,https://mirror.xyz/0x489e3e846bb550cb7b023108c...,0.0000,5,5,0.0001,0xd84035bc253d7ab99d3e05c1d1f6d1185300a602,the-governance-staking-era,[2.5],2024-11-18,...,1.0001,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03
26871,https://opensea.io/assets/optimism/0x3403ab72d...,https://mirror.xyz/0x5ee94b80d60880f25048b6158...,0.0000,1,1,0.0001,0x3403ab72df88717d4b9067fc08daf07949bab830,superchain-sunday-week-46-2024,[2.5],2024-11-18,...,1.0001,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03
26872,https://opensea.io/assets/optimism/0x9fff9c16f...,https://mirror.xyz/0x9ad0cb287b57828a2fb2b738d...,0.0000,4,4,0.0001,0x9fff9c16fde288329a2b663697ef2d04e967b4a9,the-morpho-dao-to-enable-transferability-for-m...,[2.5],2024-11-18,...,1.0001,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03
26873,https://opensea.io/assets/optimism/0x81457615f...,https://mirror.xyz/0xd5f09257a7b7d070c39e6b473...,0.0000,2,2,0.0001,0x81457615fcd852e1d51ec8273d0ef6e95e4a7da6,unlock-the-full-potential-of-safe-wallet-sign-...,[2.5],2024-11-18,...,1.0001,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03
26874,https://opensea.io/assets/optimism/0x444e61b43...,https://mirror.xyz/0x506cf76ab79b1e777bb64c173...,0.0000,1,1,0.0001,0x444e61b4386718d35384ffa3a7bac710c22d703f,how-to-play-constellation-battle-on-fuel,[2.5],2024-11-18,...,1.0001,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03

<h2>Aggiungo il numero di transazioni giornaliere su Optimism</h2>

In [33]:
#csv ottenuto da https://optimistic.etherscan.io/chart/tx
optimism_transactions = pd.read_csv("optimismTransactions.csv")
optimism_transactions

      Date(UTC)  UnixTimeStamp    Value
0     1/14/2021     1610582400     2494
1     1/15/2021     1610668800        0
2     1/16/2021     1610755200        0
3     1/17/2021     1610841600        0
4     1/18/2021     1610928000        0
...         ...            ...      ...
1507   3/1/2025     1740787200  1029402
1508   3/2/2025     1740873600  1118235
1509   3/3/2025     1740960000  1008483
1510   3/4/2025     1741046400  1161484
1511   3/5/2025     1741132800   973711

[1512 rows x 3 columns]

In [34]:
#converto Date(UTC) in datetime
optimism_transactions['Date(UTC)'] = pd.to_datetime(optimism_transactions['Date(UTC)'], format='%m/%d/%Y')

#filtro il df per le date tra il 16/08/2022 e il 18/11/2024
start_date = '2022-08-16'
end_date = '2024-11-18'
optimism_transactions = optimism_transactions[(optimism_transactions['Date(UTC)'] >= start_date) & (optimism_transactions['Date(UTC)'] <= end_date)]

optimism_transactions

      Date(UTC)  UnixTimeStamp    Value
579  2022-08-16     1660608000   176305
580  2022-08-17     1660694400   137055
581  2022-08-18     1660780800   111102
582  2022-08-19     1660867200   168662
583  2022-08-20     1660953600   140351
...         ...            ...      ...
1400 2024-11-14     1731542400  1006797
1401 2024-11-15     1731628800   950693
1402 2024-11-16     1731715200   862450
1403 2024-11-17     1731801600   883364
1404 2024-11-18     1731888000   972208

[826 rows x 3 columns]

In [35]:
#evito il warning
optimism_transactions = optimism_transactions.copy()

#rinomino la colonna della data per poter unire il dataset al mio originale
optimism_transactions.rename(columns={'Date(UTC)': 'created_date'}, inplace=True)
#la converto nel tipo stringa perché attualmente è del tipo pandas datetime e non potrei unirla
optimism_transactions['created_date'] = optimism_transactions['created_date'].astype(str)

#droppo la colonna timestamp di cui non ho bisogno
optimism_transactions.drop(columns=['UnixTimeStamp'], inplace=True)

#cambio il nome della colonna Value in un nome più comprensibile quando unirò i df
optimism_transactions.rename(columns={'Value': 'daily_transactions_optimism'}, inplace=True)

optimism_transactions

     created_date  daily_transactions_optimism
579    2022-08-16                       176305
580    2022-08-17                       137055
581    2022-08-18                       111102
582    2022-08-19                       168662
583    2022-08-20                       140351
...           ...                          ...
1400   2024-11-14                      1006797
1401   2024-11-15                       950693
1402   2024-11-16                       862450
1403   2024-11-17                       883364
1404   2024-11-18                       972208

[826 rows x 2 columns]

In [36]:
#unisco il df optimism_transactions al mio df per aggiungere il numero di transazioni giornaliere su optimism
df = pd.merge(df, optimism_transactions[['created_date', 'daily_transactions_optimism']], on='created_date', how='left')
df

,Writing NFT,Author Homepage,Total Sold(ETH),Total Sold Numbers,Total Buyers,Price(ETH),nft_address,collection,fees,created_date,...,min_usdc_usd,vol_usdc,var%_usdc,last_dai_usd,open_dai_usd,max_dai_usd,min_dai_usd,vol_dai,var%_dai,daily_transactions_optimism
0,https://opensea.io/assets/optimism/0x26bbb507d...,https://mirror.xyz/0xf4cdb62c9a66c749cdf736c43...,0.5900,59,53,0.0100,0x26bbb507daa7c0dec6a578a09f0d7ac85ff6fec5,man1f3st0,"[2.5, 10.0]",2022-08-16,...,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305
1,https://opensea.io/assets/optimism/0xfcba4d13f...,https://mirror.xyz/0x0287132a8c92e811d94e461b0...,0.0001,1,1,0.0001,0xfcba4d13fa7e4933ebf709f26d20423e5fb38f03,token-of-wealth,"[2.5, 10.0]",2022-08-16,...,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305
2,https://opensea.io/assets/optimism/0xe6d34d7f3...,https://mirror.xyz/0x3f9da1a56fac7efae92c84c90...,0.0050,1,1,0.0050,0xe6d34d7f3c34f6d90e311e302ce160b5214c2ba0,coinslist-airdrop-nft,"[2.5, 10.0]",2022-08-16,...,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305
3,https://opensea.io/assets/optimism/0x5daa524dd...,https://mirror.xyz/0xc065e02d562cc390f35693059...,0.0000,282,280,0.0001,0x5daa524dd35c0b51bac36f76e8ff89dd4866f12e,mobile-launch-trading-competition,"[2.5, 10.0]",2022-08-16,...,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305
4,https://opensea.io/assets/optimism/0xee07e40fe...,https://mirror.xyz/0x4ced9817cad891aeffbf5fb7d...,1.0000,100,93,0.0100,0xee07e40fe43ef1b1d5ed018a881742462f8cd8e3,note-is-a-key-component-of-cantos-free-public-...,"[2.5, 10.0]",2022-08-16,...,0.9997,2.725600e+08,0.01,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,https://opensea.io/assets/optimism/0xd84035bc2...,https://mirror.xyz/0x489e3e846bb550cb7b023108c...,0.0000,5,5,0.0001,0xd84035bc253d7ab99d3e05c1d1f6d1185300a602,the-governance-staking-era,[2.5],2024-11-18,...,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208
26871,https://opensea.io/assets/optimism/0x3403ab72d...,https://mirror.xyz/0x5ee94b80d60880f25048b6158...,0.0000,1,1,0.0001,0x3403ab72df88717d4b9067fc08daf07949bab830,superchain-sunday-week-46-2024,[2.5],2024-11-18,...,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208
26872,https://opensea.io/assets/optimism/0x9fff9c16f...,https://mirror.xyz/0x9ad0cb287b57828a2fb2b738d...,0.0000,4,4,0.0001,0x9fff9c16fde288329a2b663697ef2d04e967b4a9,the-morpho-dao-to-enable-transferability-for-m...,[2.5],2024-11-18,...,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208
26873,https://opensea.io/assets/optimism/0x81457615f...,https://mirror.xyz/0xd5f09257a7b7d070c39e6b473...,0.0000,2,2,0.0001,0x81457615fcd852e1d51ec8273d0ef6e95e4a7da6,unlock-the-full-potential-of-safe-wallet-sign-...,[2.5],2024-11-18,...,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208
26874,https://opensea.io/assets/optimism/0x444e61b43...,https://mirror.xyz/0x506cf76ab79b1e777bb64c173...,0.0000,1,1,0.0001,0x444e61b4386718d35384ffa3a7bac710c22d703f,how-to-play-constellation-battle-on-fuel,[2.5],2024-11-18,...,0.9988,1.220000e+09,-0.04,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208

<h2>Aggiungo il numero di indirizzi attivi su Ethereum, sia totali che come sender o receiver</h2>

In [38]:
#csv ottenuto da https://etherscan.io/chart/active-address
ethereum_addresses = pd.read_csv("ethereumAddresses.csv")
ethereum_addresses

,Date(UTC),Unique Address Total Count,Unique Address Receive Count,Unique Address Sent Count
0,07/30/2015,8894,1,8893
1,07/31/2015,0,0,0
2,08/01/2015,0,0,0
3,08/02/2015,0,0,0
4,08/03/2015,0,0,0
...,...,...,...,...
3502,03/01/2025,438433,359555,220809
3503,03/02/2025,414374,337029,210876
3504,03/03/2025,501211,408655,253337
3505,03/04/2025,504291,414988,255519
3506,03/05/2025,501321,413926,239971

In [39]:
#converto Date(UTC) in datetime
ethereum_addresses['Date(UTC)'] = pd.to_datetime(ethereum_addresses['Date(UTC)'], format='%m/%d/%Y')

#filtro il df per le date tra il 16/08/2022 e il 18/11/2024
start_date = '2022-08-16'
end_date = '2024-11-18'
ethereum_addresses = ethereum_addresses[(ethereum_addresses['Date(UTC)'] >= start_date) & (ethereum_addresses['Date(UTC)'] <= end_date)]

ethereum_addresses

,Date(UTC),Unique Address Total Count,Unique Address Receive Count,Unique Address Sent Count
2574,2022-08-16,490642,383483,220118
2575,2022-08-17,499814,391681,223722
2576,2022-08-18,504037,401637,222035
2577,2022-08-19,470152,362767,226988
2578,2022-08-20,461726,357087,211103
...,...,...,...,...
3395,2024-11-14,504697,408080,272191
3396,2024-11-15,498179,407321,254530
3397,2024-11-16,509330,414576,259758
3398,2024-11-17,493759,404827,250915
3399,2024-11-18,488779,399778,244323

In [40]:
#evito il warning
ethereum_addresses = ethereum_addresses.copy()

#rinomino la colonna della data per poter unire il dataset al mio originale
ethereum_addresses.rename(columns={'Date(UTC)': 'created_date'}, inplace=True)
#la converto nel tipo stringa perché attualmente è del tipo pandas datetime e non potrei unirla
ethereum_addresses['created_date'] = ethereum_addresses['created_date'].astype(str)

#cambio il nome delle colonne successive in nomi più comprensibile quando unirò i df
ethereum_addresses.rename(columns={'Unique Address Total Count': 'eth_active_addresses_total'}, inplace=True)
ethereum_addresses.rename(columns={'Unique Address Receive Count': 'eth_active_addresses_receiver'}, inplace=True)
ethereum_addresses.rename(columns={'Unique Address Sent Count': 'eth_active_addresses_sender'}, inplace=True)

ethereum_addresses

,created_date,eth_active_addresses_total,eth_active_addresses_receiver,eth_active_addresses_sender
2574,2022-08-16,490642,383483,220118
2575,2022-08-17,499814,391681,223722
2576,2022-08-18,504037,401637,222035
2577,2022-08-19,470152,362767,226988
2578,2022-08-20,461726,357087,211103
...,...,...,...,...
3395,2024-11-14,504697,408080,272191
3396,2024-11-15,498179,407321,254530
3397,2024-11-16,509330,414576,259758
3398,2024-11-17,493759,404827,250915
3399,2024-11-18,488779,399778,244323

In [41]:
#unisco il df ethereum_addresses al mio df per aggiungere le 3 nuove colonne sugli indirizzi unici
df = pd.merge(df, ethereum_addresses[['created_date', 'eth_active_addresses_total', 'eth_active_addresses_receiver', 'eth_active_addresses_sender']], on='created_date', how='left')
df

,Writing NFT,Author Homepage,Total Sold(ETH),Total Sold Numbers,Total Buyers,Price(ETH),nft_address,collection,fees,created_date,...,last_dai_usd,open_dai_usd,max_dai_usd,min_dai_usd,vol_dai,var%_dai,daily_transactions_optimism,eth_active_addresses_total,eth_active_addresses_receiver,eth_active_addresses_sender
0,https://opensea.io/assets/optimism/0x26bbb507d...,https://mirror.xyz/0xf4cdb62c9a66c749cdf736c43...,0.5900,59,53,0.0100,0x26bbb507daa7c0dec6a578a09f0d7ac85ff6fec5,man1f3st0,"[2.5, 10.0]",2022-08-16,...,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118
1,https://opensea.io/assets/optimism/0xfcba4d13f...,https://mirror.xyz/0x0287132a8c92e811d94e461b0...,0.0001,1,1,0.0001,0xfcba4d13fa7e4933ebf709f26d20423e5fb38f03,token-of-wealth,"[2.5, 10.0]",2022-08-16,...,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118
2,https://opensea.io/assets/optimism/0xe6d34d7f3...,https://mirror.xyz/0x3f9da1a56fac7efae92c84c90...,0.0050,1,1,0.0050,0xe6d34d7f3c34f6d90e311e302ce160b5214c2ba0,coinslist-airdrop-nft,"[2.5, 10.0]",2022-08-16,...,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118
3,https://opensea.io/assets/optimism/0x5daa524dd...,https://mirror.xyz/0xc065e02d562cc390f35693059...,0.0000,282,280,0.0001,0x5daa524dd35c0b51bac36f76e8ff89dd4866f12e,mobile-launch-trading-competition,"[2.5, 10.0]",2022-08-16,...,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118
4,https://opensea.io/assets/optimism/0xee07e40fe...,https://mirror.xyz/0x4ced9817cad891aeffbf5fb7d...,1.0000,100,93,0.0100,0xee07e40fe43ef1b1d5ed018a881742462f8cd8e3,note-is-a-key-component-of-cantos-free-public-...,"[2.5, 10.0]",2022-08-16,...,0.9999,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,https://opensea.io/assets/optimism/0xd84035bc2...,https://mirror.xyz/0x489e3e846bb550cb7b023108c...,0.0000,5,5,0.0001,0xd84035bc253d7ab99d3e05c1d1f6d1185300a602,the-governance-staking-era,[2.5],2024-11-18,...,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323
26871,https://opensea.io/assets/optimism/0x3403ab72d...,https://mirror.xyz/0x5ee94b80d60880f25048b6158...,0.0000,1,1,0.0001,0x3403ab72df88717d4b9067fc08daf07949bab830,superchain-sunday-week-46-2024,[2.5],2024-11-18,...,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323
26872,https://opensea.io/assets/optimism/0x9fff9c16f...,https://mirror.xyz/0x9ad0cb287b57828a2fb2b738d...,0.0000,4,4,0.0001,0x9fff9c16fde288329a2b663697ef2d04e967b4a9,the-morpho-dao-to-enable-transferability-for-m...,[2.5],2024-11-18,...,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323
26873,https://opensea.io/assets/optimism/0x81457615f...,https://mirror.xyz/0xd5f09257a7b7d070c39e6b473...,0.0000,2,2,0.0001,0x81457615fcd852e1d51ec8273d0ef6e95e4a7da6,unlock-the-full-potential-of-safe-wallet-sign-...,[2.5],2024-11-18,...,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323
26874,https://opensea.io/assets/optimism/0x444e61b43...,https://mirror.xyz/0x506cf76ab79b1e777bb64c173...,0.0000,1,1,0.0001,0x444e61b4386718d35384ffa3a7bac710c22d703f,how-to-play-constellation-battle-on-fuel,[2.5],2024-11-18,...,0.9995,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323

<h2>Aggiungo il numero di indirizzi attivi su OP Mainnet (Optimism)</h2>

In [43]:
#csv ottenuto da https://optimistic.etherscan.io/chart/address
optimism_addresses = pd.read_csv("optimismAddresses.csv")
optimism_addresses

      Date(UTC)  UnixTimeStamp      Value
0     1/14/2021     1610582400       5772
1     1/15/2021     1610668800       5772
2     1/16/2021     1610755200       5772
3     1/17/2021     1610841600       5772
4     1/18/2021     1610928000       5772
...         ...            ...        ...
1507   3/1/2025     1740787200  193560839
1508   3/2/2025     1740873600  193640317
1509   3/3/2025     1740960000  194034868
1510   3/4/2025     1741046400  194352757
1511   3/5/2025     1741132800  194679029

[1512 rows x 3 columns]

In [44]:
#converto Date(UTC) in datetime
optimism_addresses['Date(UTC)'] = pd.to_datetime(optimism_addresses['Date(UTC)'], format='%m/%d/%Y')

#filtro il df per le date tra il 16/08/2022 e il 18/11/2024
start_date = '2022-08-16'
end_date = '2024-11-18'
optimism_addresses = optimism_addresses[(optimism_addresses['Date(UTC)'] >= start_date) & (optimism_addresses['Date(UTC)'] <= end_date)]

optimism_addresses

      Date(UTC)  UnixTimeStamp      Value
579  2022-08-16     1660608000    1381231
580  2022-08-17     1660694400    1383031
581  2022-08-18     1660780800    1384696
582  2022-08-19     1660867200    1387113
583  2022-08-20     1660953600    1389825
...         ...            ...        ...
1400 2024-11-14     1731542400  175176482
1401 2024-11-15     1731628800  175440156
1402 2024-11-16     1731715200  175547535
1403 2024-11-17     1731801600  175721024
1404 2024-11-18     1731888000  175985199

[826 rows x 3 columns]

In [45]:
#evito il warning
optimism_addresses = optimism_addresses.copy()

#rinomino la colonna della data per poter unire il dataset al mio originale
optimism_addresses.rename(columns={'Date(UTC)': 'created_date'}, inplace=True)
#la converto nel tipo stringa perché attualmente è del tipo pandas datetime e non potrei unirla
optimism_addresses['created_date'] = optimism_addresses['created_date'].astype(str)

#droppo la colonna timestamp di cui non ho bisogno
optimism_addresses.drop(columns=['UnixTimeStamp'], inplace=True)

#cambio il nome della colonna Value in un nome più comprensibile quando unirò i df
optimism_addresses.rename(columns={'Value': 'optimism_active_addresses_total'}, inplace=True)

optimism_addresses

     created_date  optimism_active_addresses_total
579    2022-08-16                          1381231
580    2022-08-17                          1383031
581    2022-08-18                          1384696
582    2022-08-19                          1387113
583    2022-08-20                          1389825
...           ...                              ...
1400   2024-11-14                        175176482
1401   2024-11-15                        175440156
1402   2024-11-16                        175547535
1403   2024-11-17                        175721024
1404   2024-11-18                        175985199

[826 rows x 2 columns]

In [46]:
#unisco il df optimism_addresses al mio df per aggiungere il numero di indirizzi attivi giornalmente su optimism
df = pd.merge(df, optimism_addresses[['created_date', 'optimism_active_addresses_total']], on='created_date', how='left')
df

,Writing NFT,Author Homepage,Total Sold(ETH),Total Sold Numbers,Total Buyers,Price(ETH),nft_address,collection,fees,created_date,...,open_dai_usd,max_dai_usd,min_dai_usd,vol_dai,var%_dai,daily_transactions_optimism,eth_active_addresses_total,eth_active_addresses_receiver,eth_active_addresses_sender,optimism_active_addresses_total
0,https://opensea.io/assets/optimism/0x26bbb507d...,https://mirror.xyz/0xf4cdb62c9a66c749cdf736c43...,0.5900,59,53,0.0100,0x26bbb507daa7c0dec6a578a09f0d7ac85ff6fec5,man1f3st0,"[2.5, 10.0]",2022-08-16,...,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118,1381231
1,https://opensea.io/assets/optimism/0xfcba4d13f...,https://mirror.xyz/0x0287132a8c92e811d94e461b0...,0.0001,1,1,0.0001,0xfcba4d13fa7e4933ebf709f26d20423e5fb38f03,token-of-wealth,"[2.5, 10.0]",2022-08-16,...,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118,1381231
2,https://opensea.io/assets/optimism/0xe6d34d7f3...,https://mirror.xyz/0x3f9da1a56fac7efae92c84c90...,0.0050,1,1,0.0050,0xe6d34d7f3c34f6d90e311e302ce160b5214c2ba0,coinslist-airdrop-nft,"[2.5, 10.0]",2022-08-16,...,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118,1381231
3,https://opensea.io/assets/optimism/0x5daa524dd...,https://mirror.xyz/0xc065e02d562cc390f35693059...,0.0000,282,280,0.0001,0x5daa524dd35c0b51bac36f76e8ff89dd4866f12e,mobile-launch-trading-competition,"[2.5, 10.0]",2022-08-16,...,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118,1381231
4,https://opensea.io/assets/optimism/0xee07e40fe...,https://mirror.xyz/0x4ced9817cad891aeffbf5fb7d...,1.0000,100,93,0.0100,0xee07e40fe43ef1b1d5ed018a881742462f8cd8e3,note-is-a-key-component-of-cantos-free-public-...,"[2.5, 10.0]",2022-08-16,...,0.9999,1.0005,0.9995,6610000.0,0.00,176305,490642,383483,220118,1381231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,https://opensea.io/assets/optimism/0xd84035bc2...,https://mirror.xyz/0x489e3e846bb550cb7b023108c...,0.0000,5,5,0.0001,0xd84035bc253d7ab99d3e05c1d1f6d1185300a602,the-governance-staking-era,[2.5],2024-11-18,...,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323,175985199
26871,https://opensea.io/assets/optimism/0x3403ab72d...,https://mirror.xyz/0x5ee94b80d60880f25048b6158...,0.0000,1,1,0.0001,0x3403ab72df88717d4b9067fc08daf07949bab830,superchain-sunday-week-46-2024,[2.5],2024-11-18,...,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323,175985199
26872,https://opensea.io/assets/optimism/0x9fff9c16f...,https://mirror.xyz/0x9ad0cb287b57828a2fb2b738d...,0.0000,4,4,0.0001,0x9fff9c16fde288329a2b663697ef2d04e967b4a9,the-morpho-dao-to-enable-transferability-for-m...,[2.5],2024-11-18,...,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323,175985199
26873,https://opensea.io/assets/optimism/0x81457615f...,https://mirror.xyz/0xd5f09257a7b7d070c39e6b473...,0.0000,2,2,0.0001,0x81457615fcd852e1d51ec8273d0ef6e95e4a7da6,unlock-the-full-potential-of-safe-wallet-sign-...,[2.5],2024-11-18,...,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323,175985199
26874,https://opensea.io/assets/optimism/0x444e61b43...,https://mirror.xyz/0x506cf76ab79b1e777bb64c173...,0.0000,1,1,0.0001,0x444e61b4386718d35384ffa3a7bac710c22d703f,how-to-play-constellation-battle-on-fuel,[2.5],2024-11-18,...,0.9998,1.0005,0.9995,1610000.0,-0.03,972208,488779,399778,244323,175985199

<h2>Aggiungo il punteggio di ricerche su Google (1-100) in quella settimana per NFT, Optimism, Crypto, Bitcoin ed Ethereum</h2>

In [48]:
#csv ottenuti da https://trends.google.it/
google_searches_nft = pd.read_csv("google_searches_nft.csv")
google_searches_crypto = pd.read_csv("google_searches_crypto.csv")
google_searches_bitcoin = pd.read_csv("google_searches_bitcoin.csv")
google_searches_ethereum = pd.read_csv("google_searches_ethereum.csv")
google_searches_optimism = pd.read_csv("google_searches_optimism.csv")

In [49]:
google_searches_nft = google_searches_nft.reset_index().rename(columns={'index': 'created_date', 'Categoria: Tutte le categorie': 'week_google_searches_nft'}).drop(index=0).reset_index(drop=True)
google_searches_crypto = google_searches_crypto.reset_index().rename(columns={'index': 'created_date', 'Categoria: Tutte le categorie': 'week_google_searches_crypto'}).drop(index=0).reset_index(drop=True)
google_searches_bitcoin = google_searches_bitcoin.reset_index().rename(columns={'index': 'created_date', 'Categoria: Tutte le categorie': 'week_google_searches_bitcoin'}).drop(index=0).reset_index(drop=True)
google_searches_ethereum = google_searches_ethereum.reset_index().rename(columns={'index': 'created_date', 'Categoria: Tutte le categorie': 'week_google_searches_ethereum'}).drop(index=0).reset_index(drop=True)
google_searches_optimism = google_searches_optimism.reset_index().rename(columns={'index': 'created_date', 'Categoria: Tutte le categorie': 'week_google_searches_optimism'}).drop(index=0).reset_index(drop=True)

google_searches_optimism

    created_date week_google_searches_optimism
0     2022-08-14                            35
1     2022-08-21                            30
2     2022-08-28                            33
3     2022-09-04                            35
4     2022-09-11                            35
..           ...                           ...
114   2024-10-20                            38
115   2024-10-27                            35
116   2024-11-03                            46
117   2024-11-10                            44
118   2024-11-17                            43

[119 rows x 2 columns]

In [50]:
#converti temporaneamente 'created_date' di df in formato data
df['created_date'] = pd.to_datetime(df['created_date'])

#crea una colonna 'week_start_date' nei miei dataset che rappresenta l'inizio della settimana
google_searches_nft['created_date'] = pd.to_datetime(google_searches_nft['created_date'])
google_searches_nft['week_start_date'] = google_searches_nft['created_date'] - pd.to_timedelta(google_searches_nft['created_date'].dt.weekday, unit='D')
google_searches_crypto['created_date'] = pd.to_datetime(google_searches_crypto['created_date'])
google_searches_crypto['week_start_date'] = google_searches_crypto['created_date'] - pd.to_timedelta(google_searches_crypto['created_date'].dt.weekday, unit='D')
google_searches_bitcoin['created_date'] = pd.to_datetime(google_searches_bitcoin['created_date'])
google_searches_bitcoin['week_start_date'] = google_searches_bitcoin['created_date'] - pd.to_timedelta(google_searches_bitcoin['created_date'].dt.weekday, unit='D')
google_searches_ethereum['created_date'] = pd.to_datetime(google_searches_ethereum['created_date'])
google_searches_ethereum['week_start_date'] = google_searches_ethereum['created_date'] - pd.to_timedelta(google_searches_ethereum['created_date'].dt.weekday, unit='D')
google_searches_optimism['created_date'] = pd.to_datetime(google_searches_optimism['created_date'])
google_searches_optimism['week_start_date'] = google_searches_optimism['created_date'] - pd.to_timedelta(google_searches_optimism['created_date'].dt.weekday, unit='D')

#esegui merge_asof per unire il primo df sulla base della settimana
df = pd.merge_asof(df.sort_values('created_date'), 
                          google_searches_nft.sort_values('created_date'),
                          on='created_date',
                          direction='backward')

#rimuovi week_start_date per poter unire anche gli altri dataset senza problemi
df = df.drop(columns=['week_start_date'])

#esegui merge_asof per unire il secondo df sulla base della settimana
df = pd.merge_asof(df.sort_values('created_date'), 
                          google_searches_crypto.sort_values('created_date'),
                          on='created_date',
                          direction='backward')

#rimuovi week_start_date per poter unire anche gli altri dataset senza problemi
df = df.drop(columns=['week_start_date'])

#esegui merge_asof per unire il terzo df sulla base della settimana
df = pd.merge_asof(df.sort_values('created_date'), 
                          google_searches_bitcoin.sort_values('created_date'),
                          on='created_date',
                          direction='backward')

#rimuovi week_start_date per poter unire anche gli altri dataset senza problemi
df = df.drop(columns=['week_start_date'])

#esegui merge_asof per unire il quarto df sulla base della settimana
df = pd.merge_asof(df.sort_values('created_date'), 
                          google_searches_ethereum.sort_values('created_date'),
                          on='created_date',
                          direction='backward')

#rimuovi week_start_date per poter unire anche gli altri dataset senza problemi
df = df.drop(columns=['week_start_date'])

#esegui merge_asof per unire il quinto df sulla base della settimana
df = pd.merge_asof(df.sort_values('created_date'), 
                          google_searches_optimism.sort_values('created_date'),
                          on='created_date',
                          direction='backward')

#rimuovi week_start_date definitivamente perché non mi serve più
df = df.drop(columns=['week_start_date'])

#riconverti created_date in str
df['created_date'] = df['created_date'].astype(str)

df

,Writing NFT,Author Homepage,Total Sold(ETH),Total Sold Numbers,Total Buyers,Price(ETH),nft_address,collection,fees,created_date,...,daily_transactions_optimism,eth_active_addresses_total,eth_active_addresses_receiver,eth_active_addresses_sender,optimism_active_addresses_total,week_google_searches_nft,week_google_searches_crypto,week_google_searches_bitcoin,week_google_searches_ethereum,week_google_searches_optimism
0,https://opensea.io/assets/optimism/0x26bbb507d...,https://mirror.xyz/0xf4cdb62c9a66c749cdf736c43...,0.5900,59,53,0.0100,0x26bbb507daa7c0dec6a578a09f0d7ac85ff6fec5,man1f3st0,"[2.5, 10.0]",2022-08-16,...,176305,490642,383483,220118,1381231,74,49,36,56,35
1,https://opensea.io/assets/optimism/0x3e21e1d8e...,https://mirror.xyz/0x4ced9817cad891aeffbf5fb7d...,2.0000,200,198,0.0100,0x3e21e1d8e89d675aca9708aee0ae05c7f6622c29,canto-genesis,"[2.5, 10.0]",2022-08-16,...,176305,490642,383483,220118,1381231,74,49,36,56,35
2,https://opensea.io/assets/optimism/0xdd81b24ec...,https://mirror.xyz/0xb8dbf8e09c1cb83da9632e137...,0.0001,1,1,0.0001,0xdd81b24ec7813d0fc8570bfd5008271037122349,niswap-airdrop-iron,"[2.5, 10.0]",2022-08-16,...,176305,490642,383483,220118,1381231,74,49,36,56,35
3,https://opensea.io/assets/optimism/0xd283a8373...,https://mirror.xyz/0xc065e02d562cc390f35693059...,0.0000,53,53,0.0001,0xd283a8373ada1285547bba0d36556ea47ac25c54,trading-on-kwenta-mobile,"[2.5, 10.0]",2022-08-16,...,176305,490642,383483,220118,1381231,74,49,36,56,35
4,https://opensea.io/assets/optimism/0x3fada15d6...,https://mirror.xyz/0x0df68ee531dab63d651132c7f...,0.0000,2,2,0.0001,0x3fada15d698a86a23e871d9b1bea9877e38e1e6b,some-words-about-rabbithole,"[2.5, 10.0]",2022-08-16,...,176305,490642,383483,220118,1381231,74,49,36,56,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,https://opensea.io/assets/optimism/0x81457615f...,https://mirror.xyz/0xd5f09257a7b7d070c39e6b473...,0.0000,2,2,0.0001,0x81457615fcd852e1d51ec8273d0ef6e95e4a7da6,unlock-the-full-potential-of-safe-wallet-sign-...,[2.5],2024-11-18,...,972208,488779,399778,244323,175985199,26,100,84,53,43
26871,https://opensea.io/assets/optimism/0xd84035bc2...,https://mirror.xyz/0x489e3e846bb550cb7b023108c...,0.0000,5,5,0.0001,0xd84035bc253d7ab99d3e05c1d1f6d1185300a602,the-governance-staking-era,[2.5],2024-11-18,...,972208,488779,399778,244323,175985199,26,100,84,53,43
26872,https://opensea.io/assets/optimism/0x3403ab72d...,https://mirror.xyz/0x5ee94b80d60880f25048b6158...,0.0000,1,1,0.0001,0x3403ab72df88717d4b9067fc08daf07949bab830,superchain-sunday-week-46-2024,[2.5],2024-11-18,...,972208,488779,399778,244323,175985199,26,100,84,53,43
26873,https://opensea.io/assets/optimism/0x9fff9c16f...,https://mirror.xyz/0x9ad0cb287b57828a2fb2b738d...,0.0000,4,4,0.0001,0x9fff9c16fde288329a2b663697ef2d04e967b4a9,the-morpho-dao-to-enable-transferability-for-m...,[2.5],2024-11-18,...,972208,488779,399778,244323,175985199,26,100,84,53,43
26874,https://opensea.io/assets/optimism/0x444e61b43...,https://mirror.xyz/0x506cf76ab79b1e777bb64c173...,0.0000,1,1,0.0001,0x444e61b4386718d35384ffa3a7bac710c22d703f,how-to-play-constellation-battle-on-fuel,[2.5],2024-11-18,...,972208,488779,399778,244323,175985199,26,100,84,53,43

In [51]:
import numpy as np

df.drop(columns=['Success'], inplace=True)
df.drop(columns=['SuccessBinary'], inplace=True)

df.loc[:, 'Success'] = df['Total Sold Numbers'] * df['Price(ETH)'] * 100000

#threshold basata sulla mediana di success
threshold = df['Success'].median()

#creo la colonna SuccessBinary per classificazione
df['SuccessBinary'] = np.where(df['Success'] >= threshold, 1, 0)

counts = df['SuccessBinary'].value_counts()
print(counts)

df

SuccessBinary
1    13552
0    13323
Name: count, dtype: int64

,Writing NFT,Author Homepage,Total Sold(ETH),Total Sold Numbers,Total Buyers,Price(ETH),nft_address,collection,fees,created_date,...,eth_active_addresses_receiver,eth_active_addresses_sender,optimism_active_addresses_total,week_google_searches_nft,week_google_searches_crypto,week_google_searches_bitcoin,week_google_searches_ethereum,week_google_searches_optimism,Success,SuccessBinary
0,https://opensea.io/assets/optimism/0x26bbb507d...,https://mirror.xyz/0xf4cdb62c9a66c749cdf736c43...,0.5900,59,53,0.0100,0x26bbb507daa7c0dec6a578a09f0d7ac85ff6fec5,man1f3st0,"[2.5, 10.0]",2022-08-16,...,383483,220118,1381231,74,49,36,56,35,59000.0,1
1,https://opensea.io/assets/optimism/0x3e21e1d8e...,https://mirror.xyz/0x4ced9817cad891aeffbf5fb7d...,2.0000,200,198,0.0100,0x3e21e1d8e89d675aca9708aee0ae05c7f6622c29,canto-genesis,"[2.5, 10.0]",2022-08-16,...,383483,220118,1381231,74,49,36,56,35,200000.0,1
2,https://opensea.io/assets/optimism/0xdd81b24ec...,https://mirror.xyz/0xb8dbf8e09c1cb83da9632e137...,0.0001,1,1,0.0001,0xdd81b24ec7813d0fc8570bfd5008271037122349,niswap-airdrop-iron,"[2.5, 10.0]",2022-08-16,...,383483,220118,1381231,74,49,36,56,35,10.0,0
3,https://opensea.io/assets/optimism/0xd283a8373...,https://mirror.xyz/0xc065e02d562cc390f35693059...,0.0000,53,53,0.0001,0xd283a8373ada1285547bba0d36556ea47ac25c54,trading-on-kwenta-mobile,"[2.5, 10.0]",2022-08-16,...,383483,220118,1381231,74,49,36,56,35,530.0,1
4,https://opensea.io/assets/optimism/0x3fada15d6...,https://mirror.xyz/0x0df68ee531dab63d651132c7f...,0.0000,2,2,0.0001,0x3fada15d698a86a23e871d9b1bea9877e38e1e6b,some-words-about-rabbithole,"[2.5, 10.0]",2022-08-16,...,383483,220118,1381231,74,49,36,56,35,20.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26870,https://opensea.io/assets/optimism/0x81457615f...,https://mirror.xyz/0xd5f09257a7b7d070c39e6b473...,0.0000,2,2,0.0001,0x81457615fcd852e1d51ec8273d0ef6e95e4a7da6,unlock-the-full-potential-of-safe-wallet-sign-...,[2.5],2024-11-18,...,399778,244323,175985199,26,100,84,53,43,20.0,0
26871,https://opensea.io/assets/optimism/0xd84035bc2...,https://mirror.xyz/0x489e3e846bb550cb7b023108c...,0.0000,5,5,0.0001,0xd84035bc253d7ab99d3e05c1d1f6d1185300a602,the-governance-staking-era,[2.5],2024-11-18,...,399778,244323,175985199,26,100,84,53,43,50.0,1
26872,https://opensea.io/assets/optimism/0x3403ab72d...,https://mirror.xyz/0x5ee94b80d60880f25048b6158...,0.0000,1,1,0.0001,0x3403ab72df88717d4b9067fc08daf07949bab830,superchain-sunday-week-46-2024,[2.5],2024-11-18,...,399778,244323,175985199,26,100,84,53,43,10.0,0
26873,https://opensea.io/assets/optimism/0x9fff9c16f...,https://mirror.xyz/0x9ad0cb287b57828a2fb2b738d...,0.0000,4,4,0.0001,0x9fff9c16fde288329a2b663697ef2d04e967b4a9,the-morpho-dao-to-enable-transferability-for-m...,[2.5],2024-11-18,...,399778,244323,175985199,26,100,84,53,43,40.0,1
26874,https://opensea.io/assets/optimism/0x444e61b43...,https://mirror.xyz/0x506cf76ab79b1e777bb64c173...,0.0000,1,1,0.0001,0x444e61b4386718d35384ffa3a7bac710c22d703f,how-to-play-constellation-battle-on-fuel,[2.5],2024-11-18,...,399778,244323,175985199,26,100,84,53,43,10.0,0

In [52]:
df.to_csv("mirror_publications_definitive.csv", index=False)